name: docker

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_PASSWORD:
        required: false
    inputs:
      images:
        type: string
        required: true
      working_directory:
        type: string
        required: false
      context:
        type: string
        required: false
      dockerfile:
        type: string
        required: false
      target:
        type: string
        required: false
      cache_from:
        type: string
        required: false
      platforms:
        type: string
        required: false
      publish:
        type: boolean
        required: false

jobs:

  meta:
    runs-on: ubuntu-latest

    outputs:
      labels: ${{ steps.metadata.outputs.labels }}
      tags: ${{ steps.metadata.outputs.tags }}
      platforms: ${{ steps.platforms.outputs.build }}

    steps:

      - id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.images }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}

      - id: platforms
        uses: kanga333/json-array-builder@v0.1.0
        with:
          str: ${{ inputs.platforms || 'linux/amd64' }}
          separator: "newline"

  test:
    runs-on: ubuntu-latest
    needs: [ meta ]

    defaults:
      run:
        working-directory: ${{ inputs.working_directory || '.' }}

    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(needs.meta.outputs.platforms) }}

    env:
      TEST_TAG: sut:latest

    steps:

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - id: build
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ needs.meta.outputs.labels }}
          cache-to: type=local,dest=/tmp/artifacts
          cache-from: |
            type=gha
            ${{ needs.meta.outputs.tags }}
            ${{ inputs.cache_from }}
            type=local,src=/tmp/artifacts
          context: ${{ inputs.context }}
          target: ${{ inputs.target }}
          tags: ${{ env.TEST_TAG }}
          load: true

      - run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml up --no-build --exit-code-from sut

      - id: digest
        run: |
          echo "::set-output name=sha256::$(echo ${{ steps.build.outputs.digest }} | awk -F ':' '{ print $2 }')"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.digest.outputs.sha256 }}
          path: /tmp/artifacts/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: [ meta, test ]
    if: ${{ inputs.publish == true }}

    steps:

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: actions/download-artifact@v3
        with:
          path: /tmp/cache

      - uses: docker/login-action@v2
        if: ${{ contains(inputs.images, 'ghcr.io') }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v2
        if: ${{ contains(inputs.images, 'docker.io') }}
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          platforms: ${{ inputs.platforms }}
          labels: ${{ needs.meta.outputs.labels }}
          cache-to: type=gha,mode=max
          # cache-from: |
          #   type=gha
          #   ${{ needs.meta.outputs.tags }}
          #   ${{ inputs.cache_from }}
          #   type=local,src=/tmp/cache/*
          cache-from: type=local,src=/tmp/cache/*
          context: ${{ inputs.context }}
          target: ${{ inputs.target }}
          tags: ${{ needs.meta.outputs.tags }}
          push: ${{ inputs.publish == true }}

      - uses: peter-evans/dockerhub-description@v3
        if: ${{ contains(inputs.images, 'docker.io') && github.event_name != 'pull_request' }} 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ fromJSON(needs.inputs.outputs.json).sut }}

  cleanup:
    runs-on: ubuntu-latest

    steps:

      - uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 hour'
