name: docker

on:
  push:
    tags:
      - "*"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  image: "klutchell/unbound"
  platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
  registries: "docker.io,ghcr.io"

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      registry:
        image: registry:2.7.1
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/${{ env.image }},ghcr.io/${{ env.image }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}

      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - uses: docker/build-push-action@v3
        with:
          platforms: ${{ env.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: localhost:5000/${{ env.image }}:local
          cache-to: type=gha,mode=max
          cache-from: |
            type=gha
            ${{ steps.meta.outputs.tags }}
            docker.io/${{ env.image }}:${{ github.base_ref }}
            ghcr.io/${{ env.image }}:${{ github.base_ref }}
          push: true

      - uses: docker/setup-qemu-action@v2

      - name: Run tests
        run: |
          for platform in $(tr ',' '\n' <<< "${{ env.platforms }}") ; do
            docker pull --platform ${platform} localhost:5000/${{ env.image }}:local
            docker run --rm localhost:5000/${{ env.image }}:local -V 2>&1 | tee /dev/stderr | grep -wq "$(head -n1 VERSION)"
            docker run --rm --entrypoint unbound-checkconf localhost:5000/${{ env.image }}:local -o root-hints 2>&1 | tee /dev/stderr | grep -wq "/etc/unbound/root.hints"
            docker run --rm -d --name sut localhost:5000/${{ env.image }}:local
            docker exec sut dig sigok.verteiltesysteme.net @127.0.0.1 +dnssec | tee /dev/stderr | grep -wq NOERROR || { docker logs sut ; exit 1 ; }
            docker exec sut dig sigfail.verteiltesysteme.net @127.0.0.1 +dnssec | tee /dev/stderr | grep -wq SERVFAIL || { docker logs sut ; exit 1 ; }
            docker logs sut
            docker stop sut
          done

      - uses: docker/login-action@v2
        if: github.actor == github.repository_owner
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v2
        if: github.actor == github.repository_owner
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: akhilerm/tag-push-action@v2.0.0
        if: github.actor == github.repository_owner
        with:
          src: localhost:5000/${{ env.image }}:local
          dst: |
            ${{ steps.meta.outputs.tags }}

      - uses: peter-evans/dockerhub-description@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.image }}
