name: Build and Push Docker Image (Daily)

on:
  schedule:
    - cron: "0 0 * * *"  # Schedule the workflow to run daily at midnight (UTC time). Adjust the time if needed.
  workflow_dispatch:  # Manual run trigger
    inputs:
      trigger-build:
        description: 'Trigger a manual build and push'
        default: 'true'

jobs:
  build_and_push:
    runs-on: ubuntu-22.04

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (replace with the appropriate registry if using something else)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx (needed for multi-platform builds)
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7

      # Build and Push Docker Image using QEMU for multi-arch
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: . # Path to the directory containing the Dockerfile (subfolder)
          push: true
          tags: noxcis/unbound:latest
          platforms: linux/amd64,linux/arm64
          # Uncomment the following line if you want to disable caching (useful for debugging)
          # no-cache: true

      # Optional: add a post-build step for notifications or further checks (e.g., send a message on Slack)
